// Programmatic landing pages for the Smoke Time Calculator, one per protein the
// calculator supports. Each preset gets a unique, search-intent URL
// (e.g. /tools/smoke-time/brisket/) with the calculator pre-set to that protein,
// substantive protein-specific copy, FAQs, and a link to the matching guide.
// Imported by both the [preset] route and the sitemap so the two never drift.
//
// `protein` MUST match a SMOKE_TIMES entry in lib/woods.js exactly.

export const SMOKE_PRESETS = [
  {
    slug: "brisket",
    protein: "Brisket (packer)",
    weight: 13,
    h1: "Brisket Smoke Time Calculator",
    title: "Brisket Smoke Time Calculator, How Long to Smoke a Brisket",
    desc: "Calculate how long to smoke a brisket by weight and pit temp, and get a start time so it rests and is ready when you serve. Plan around the stall.",
    keywords: ["brisket smoke time", "how long to smoke a brisket", "brisket cook time calculator", "when to start a brisket"],
    intro: "Estimate how long your brisket will take at smoking temperature and work backward from dinner so it finishes with time to rest. A packer at 250°F runs roughly 75–90 minutes per pound, but cook to probe-tender (~203°F), not the clock.",
    howLong: "At a 250°F pit, a whole packer brisket takes about 75–90 minutes per pound, so a 13 lb brisket lands around 16–19 hours. The biggest variable is the stall, where evaporative cooling parks the internal temp in the 150–170°F range for an hour or more.",
    tips: [
      "Plan for a stall between 150–170°F. Wrapping in butcher paper or foil pushes through it faster and protects the bark.",
      "Cook to feel, probe-tender around 203°F internal, not to a fixed time.",
      "Rest at least an hour (longer is fine) wrapped in a dry cooler. The calculator already builds your rest into the start time.",
      "Start early. Finishing ahead is easy to hold; finishing late is not.",
    ],
    faqs: [
      { q: "How long to smoke a 13 lb brisket?", a: "At 250°F, plan on roughly 16–19 hours (about 75–90 minutes per pound) plus at least an hour of rest. The stall can add time, so start early and pull at ~203°F probe-tender." },
      { q: "How long per pound to smoke a brisket?", a: "About 75–90 minutes per pound at a 250°F pit. Lower pit temps and a long stall push it longer; wrapping shortens it." },
      { q: "Should I smoke brisket at 225°F or 250°F?", a: "Both work. 225°F adds a little smoke time but runs longer; 250°F is more forgiving for finishing on schedule. Either way, pull at probe-tender rather than a set time." },
    ],
    guide: { href: "/guides/how-to-smoke-a-brisket/", label: "How to Smoke a Brisket" },
  },
  {
    slug: "pork-butt",
    protein: "Pork shoulder / butt",
    weight: 8,
    h1: "Pork Butt Smoke Time Calculator",
    title: "Pork Butt Smoke Time Calculator, Pulled Pork Cook Time",
    desc: "Work out how long to smoke a pork butt (Boston butt) for pulled pork by weight and pit temp, with a start time that includes the stall and rest.",
    keywords: ["pork butt smoke time", "how long to smoke a pork butt", "pulled pork cook time", "boston butt smoking time"],
    intro: "Pork shoulder is the most forgiving big smoke there is. Estimate the cook by weight and pit temp, then back-time it from dinner. At 250°F it runs about 75–105 minutes per pound and pulls best around 203°F.",
    howLong: "At 250°F, a bone-in pork butt takes roughly 75–105 minutes per pound, so an 8 lb butt usually runs 10–14 hours. The wide range is the stall, pork shoulder has plenty of fat and connective tissue, so it can park in the 150–170°F range for a good while.",
    tips: [
      "It's hard to overcook. Pull when it's probe-tender and the bone wiggles free, around 203°F.",
      "Wrap once the bark is set (around the stall) to speed things up and keep it moist.",
      "Rest 30–60 minutes before pulling so the juices redistribute.",
      "Buying for a crowd? Pulled pork loses ~40–50% of its raw weight, check the meat-per-person calculator.",
    ],
    faqs: [
      { q: "How long to smoke an 8 lb pork butt?", a: "At 250°F, plan on about 10–14 hours (roughly 75–105 minutes per pound) plus a 30–60 minute rest. Cook to ~203°F probe-tender, not a set time." },
      { q: "How long per pound to smoke pork shoulder?", a: "About 75–105 minutes per pound at 225–250°F. The stall around 150–170°F is the main reason times vary." },
      { q: "Can you overcook pulled pork?", a: "It's very forgiving, but pushed far past 205°F it can turn mushy. Pull at probe-tender around 203°F for the best texture." },
    ],
    guide: { href: "/guides/how-to-smoke-a-pork-butt/", label: "How to Smoke a Pork Butt" },
  },
  {
    slug: "spare-ribs",
    protein: "Spare ribs",
    weight: 3,
    h1: "Spare Ribs Smoke Time Calculator",
    title: "Spare Ribs Smoke Time Calculator, How Long to Smoke Ribs",
    desc: "How long to smoke spare ribs at 250°F, with a start time worked back from your meal. Roughly 5–6 hours total; the 3-2-1 method is a common starting point.",
    keywords: ["spare ribs smoke time", "how long to smoke spare ribs", "3-2-1 ribs time", "st louis ribs smoke time"],
    intro: "Spare ribs (including St. Louis cut) are timed by the rack, not by the pound. At 250°F plan on about 5–6 hours and finish on the bend test, not an internal temperature.",
    howLong: "At a 250°F pit, a rack of spare ribs takes roughly 5–6 hours total. The popular 3-2-1 method (3 hours open, 2 hours wrapped, 1 hour saucing unwrapped) is a reliable starting point you can dial in to your cooker.",
    tips: [
      "Judge doneness with the bend test: lift the rack and it should crack on the surface and bow, not snap.",
      "3-2-1 is a guideline, trim the wrapped stage if you like more bite, extend it for fall-off-the-bone.",
      "Spritz during the open stage to keep the surface from drying before the bark sets.",
      "St. Louis-cut spares are more even than full spares and finish a touch faster.",
    ],
    faqs: [
      { q: "How long does it take to smoke spare ribs?", a: "About 5–6 hours at 250°F. The 3-2-1 method (3 hrs open, 2 hrs wrapped, 1 hr unwrapped) is a common framework." },
      { q: "What is the 3-2-1 method for ribs?", a: "Three hours smoking unwrapped, two hours wrapped to tenderize, then about one hour unwrapped to set the sauce and bark. It's tuned for spare ribs; baby backs need less wrapped time." },
      { q: "How do you know when ribs are done?", a: "Use the bend test, lift the rack with tongs and the surface should crack and the rack bow. Ribs finish on feel, not a target internal temp." },
    ],
    guide: { href: "/guides/how-to-smoke-ribs/", label: "How to Smoke Ribs" },
  },
  {
    slug: "baby-back-ribs",
    protein: "Baby back ribs",
    weight: 2,
    h1: "Baby Back Ribs Smoke Time Calculator",
    title: "Baby Back Ribs Smoke Time Calculator, Cook Time & 2-2-1",
    desc: "How long to smoke baby back ribs at 250°F, roughly 4–5 hours, with a start time worked back from your meal. Try the 2-2-1 method and the bend test.",
    keywords: ["baby back ribs smoke time", "how long to smoke baby back ribs", "2-2-1 ribs", "baby back ribs 250"],
    intro: "Baby back ribs are leaner and shorter than spares, so they cook faster. At 250°F plan on about 4–5 hours and finish on the bend test rather than a thermometer.",
    howLong: "At a 250°F pit, baby back ribs take roughly 4–5 hours total. The 2-2-1 method (2 hours open, 2 hours wrapped, 1 hour unwrapped) suits them better than the longer 3-2-1 used for spare ribs, because they have less connective tissue.",
    tips: [
      "Use 2-2-1, not 3-2-1, baby backs overcook faster than spares.",
      "Check with the bend test: a good rack cracks on top and bows when lifted.",
      "Pull the membrane off the bone side so the rub and smoke penetrate.",
      "Cut back the wrapped stage if you prefer ribs with a little tooth.",
    ],
    faqs: [
      { q: "How long to smoke baby back ribs at 250?", a: "About 4–5 hours. The 2-2-1 method (2 hrs open, 2 hrs wrapped, 1 hr unwrapped) is a solid starting point." },
      { q: "Are baby back ribs faster than spare ribs?", a: "Yes. Baby backs are leaner and shorter, so they finish roughly an hour sooner, use 2-2-1 instead of 3-2-1." },
      { q: "Do you smoke baby backs to a temperature?", a: "Ribs are judged by feel, not temp. Use the bend test; if you probe between bones it should feel like soft butter." },
    ],
    guide: { href: "/guides/how-to-smoke-ribs/", label: "How to Smoke Ribs" },
  },
  {
    slug: "whole-chicken",
    protein: "Whole chicken",
    weight: 5,
    h1: "Whole Chicken Smoke Time Calculator",
    title: "Smoked Whole Chicken Time Calculator, How Long & What Temp",
    desc: "How long to smoke a whole chicken, with a start time for your meal. Smoke hotter (around 275°F) for crispier skin and pull at 165°F in the breast.",
    keywords: ["smoked whole chicken time", "how long to smoke a whole chicken", "smoked chicken temp", "whole chicken 275"],
    intro: "Whole chicken smokes faster than the big cuts and rewards a higher pit temp. Around 275°F it runs about 30–45 minutes per pound, and you cook to a safe 165°F in the breast, not to the clock.",
    howLong: "At a 275°F pit, a 5 lb whole chicken takes roughly 2.5–3.75 hours. Running the pit hotter than low-and-slow helps render the skin so it isn't rubbery, while the meat still picks up plenty of smoke.",
    tips: [
      "Smoke hotter (275–300°F), low temps leave chicken skin rubbery.",
      "Pull at a safe 165°F in the thickest part of the breast (USDA FSIS).",
      "Dry-brine the day before for seasoned, crispier skin.",
      "Spatchcock (remove the backbone) for faster, more even cooking.",
    ],
    faqs: [
      { q: "How long to smoke a whole chicken?", a: "About 2.5–3.75 hours for a 5 lb bird at 275°F (roughly 30–45 minutes per pound). Always confirm 165°F in the breast." },
      { q: "What temperature do you smoke a whole chicken at?", a: "Around 275–300°F. Higher than typical low-and-slow temps so the skin renders and crisps instead of turning rubbery." },
      { q: "What internal temp is smoked chicken done?", a: "165°F in the thickest part of the breast is the USDA safe minimum. Thighs are fine higher, around 175°F, where they're more tender." },
    ],
    guide: { href: "/guides/how-to-smoke-a-whole-chicken/", label: "How to Smoke a Whole Chicken" },
  },
  {
    slug: "turkey",
    protein: "Turkey (whole)",
    weight: 14,
    h1: "Smoked Turkey Time Calculator",
    title: "Smoked Turkey Time Calculator, How Long to Smoke a Turkey",
    desc: "How long to smoke a whole turkey, with a start time worked back from dinner. Smoke at ~300°F for safe, non-rubbery skin and pull at 165°F in the breast.",
    keywords: ["smoked turkey time", "how long to smoke a turkey", "smoked turkey per pound", "turkey smoke temp"],
    intro: "A smoked turkey is a holiday centerpiece, and timing matters when the whole meal waits on it. At around 300°F it runs about 25–35 minutes per pound, finishing at a safe 165°F in the breast.",
    howLong: "At a 300°F pit, a 14 lb turkey takes roughly 6–8 hours. Smoking turkey hotter than other low-and-slow cooks is intentional: it keeps the bird moving through the food-safety danger zone and renders the skin so it isn't rubbery.",
    tips: [
      "Smoke at 300°F or higher, low temps leave poultry skin rubbery and slow the safe-zone transit.",
      "Pull at 165°F in the thickest part of the breast (USDA FSIS).",
      "Brine or dry-brine ahead for a juicier, well-seasoned bird.",
      "Stay under ~14–15 lb for smoking; larger birds spend too long in the danger zone, smoke two smaller ones instead.",
    ],
    faqs: [
      { q: "How long to smoke a 14 lb turkey?", a: "About 6–8 hours at 300°F (roughly 25–35 minutes per pound). Always cook to 165°F in the breast rather than by time alone." },
      { q: "What temp do you smoke a turkey at?", a: "Around 300°F. Higher than most low-and-slow cooks so the bird clears the danger zone safely and the skin renders." },
      { q: "Should you brine a turkey before smoking?", a: "It helps. A wet or dry brine seasons the meat and keeps it juicier through a long smoke. Pat the skin dry before it goes on for better color." },
    ],
    guide: { href: "/guides/how-to-smoke-a-turkey/", label: "How to Smoke a Turkey" },
  },
  {
    slug: "pork-loin",
    protein: "Pork loin",
    weight: 3,
    h1: "Smoked Pork Loin Time Calculator",
    title: "Smoked Pork Loin Time Calculator, How Long & What Temp",
    desc: "How long to smoke a pork loin without drying it out, with a start time for your meal. It's lean, pull at 145°F and rest. Don't confuse it with pork butt.",
    keywords: ["smoked pork loin time", "how long to smoke a pork loin", "pork loin smoke temp", "pork loin 145"],
    intro: "Pork loin is lean, so it's all about not overshooting. At 250°F it runs about 30–45 minutes per pound and pulls at 145°F followed by a rest, a completely different cook from a fatty pork butt.",
    howLong: "At a 250°F pit, a 3 lb pork loin takes roughly 1.5–2.25 hours. Because it's lean, the margin between juicy and dry is small, lean on a thermometer and pull right at 145°F, then rest.",
    tips: [
      "Don't confuse pork loin with pork shoulder/butt, loin is lean and cooks fast.",
      "Pull at 145°F (USDA FSIS) and rest 10 minutes; carryover finishes it.",
      "A light dry brine and a fat cap up help keep it moist.",
      "Skip wrapping, there's no long stall to push through on a lean cut.",
    ],
    faqs: [
      { q: "How long to smoke a pork loin?", a: "About 1.5–2.25 hours for a 3 lb loin at 250°F (roughly 30–45 minutes per pound). Pull at 145°F and rest." },
      { q: "What temp is smoked pork loin done?", a: "145°F internal (USDA FSIS) followed by a short rest. It's lean, so going much higher dries it out." },
      { q: "Is pork loin the same as pork butt?", a: "No. Pork loin is a lean roast that cooks quickly to 145°F; pork butt (shoulder) is fatty and goes to ~203°F for pulled pork. They aren't interchangeable." },
    ],
    guide: { href: "/guides/how-to-smoke-a-pork-loin/", label: "How to Smoke a Pork Loin" },
  },
  {
    slug: "beef-short-ribs",
    protein: "Beef short ribs",
    weight: 4,
    h1: "Beef Short Ribs Smoke Time Calculator",
    title: "Beef Short Ribs Smoke Time Calculator, Cook Time & Temp",
    desc: "How long to smoke beef short ribs (plate ribs), with a start time for your meal. Treat them like mini briskets, cook to probe-tender around 203°F.",
    keywords: ["beef short ribs smoke time", "how long to smoke beef ribs", "plate ribs smoke time", "beef short ribs 203"],
    intro: "Beef short ribs, especially meaty plate ribs, smoke like miniature briskets. At 275°F they run about 60–90 minutes per pound and finish probe-tender around 203°F, with the same kind of stall.",
    howLong: "At a 275°F pit, a 4 lb plate of beef short ribs takes roughly 4–6 hours. Like brisket, they have heavy connective tissue and will stall, so cook to feel, probe-tender near 203°F, rather than to a clock.",
    tips: [
      "Treat them like small briskets: low-and-slow to probe-tender around 203°F.",
      "Expect a stall; you can wrap to push through it, though many cook plate ribs unwrapped for bark.",
      "Leave the fat cap and membrane choices to the cut, plate ribs render beautifully.",
      "They're done when a probe slides between the bones like warm butter.",
    ],
    faqs: [
      { q: "How long to smoke beef short ribs?", a: "About 4–6 hours for a 4 lb plate at 275°F (roughly 60–90 minutes per pound). Cook to probe-tender around 203°F, not a set time." },
      { q: "What temp are beef short ribs done?", a: "Around 203°F probe-tender, the same target as brisket. The connective tissue needs to render for that signature texture." },
      { q: "Are beef short ribs like brisket?", a: "Very much so, heavy marbling and connective tissue, a stall, and a ~203°F probe-tender finish. They're often called 'brisket on a stick.'" },
    ],
    guide: { href: "/guides/how-to-smoke-beef-ribs/", label: "How to Smoke Beef Ribs" },
  },
];

export const SMOKE_PRESET_SLUGS = SMOKE_PRESETS.map((p) => p.slug);

export function getSmokePreset(slug) {
  return SMOKE_PRESETS.find((p) => p.slug === slug);
}
